/**
 * Wikipedia scraper — fetch research data cho 50 storms
 * Chạy: npx tsx scripts/fetch-wikipedia.ts
 * Output: supabase/seed/storms-meta.json
 *
 * Sau khi chạy xong, dùng supabase dashboard SQL Editor để chạy:
 * supabase/migrations/0002_seed_storms.sql
 */
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { STORMS, type StormEntry } from "./storms-list";

const WIKI_API = "https://en.wikipedia.org/api/rest_v1/page/summary";
const WIKI_PARSE = "https://en.wikipedia.org/w/api.php";

type WikiSummary = {
  title: string;
  description: string;
  extract: string;
  thumbnail?: { source: string; width: number; height: number };
  originalimage?: { source: string };
};

type StormMeta = StormEntry & {
  summary: string;
  ogImageUrl: string | null;
  peakWindKmh: number | null;
  peakPressure: number | null;
  fatalities: number | null;
  damageUsd: number | null;
  affectedAreas: string[];
  sources: { title: string; url: string; type: string }[];
  funFacts: string[];
  researchMd: string;
};

async function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

function extractNumbers(text: string): { wind?: number; pressure?: number; deaths?: number } {
  const wind = text.match(/(\d{2,3})\s*mph/)?.[1];
  const pressure = text.match(/(\d{3})\s*mb/)?.[1];
  const deaths = text.match(/(\d[\d,]+)\s*(deaths?|fatalities|killed|people died)/i)?.[1]?.replace(/,/g, "");
  return {
    wind: wind ? Math.round(parseInt(wind) * 1.60934) : undefined,
    pressure: pressure ? parseInt(pressure) : undefined,
    deaths: deaths ? parseInt(deaths) : undefined,
  };
}

function buildResearchMd(storm: StormEntry, summary: WikiSummary, extract: string): string {
  const intro = summary.extract || extract;
  return `## Overview\n\n${intro}\n\n## Key Facts\n\nSee structured data above.\n\n## Sources\n\n- [Wikipedia](https://en.wikipedia.org/wiki/${storm.wikiTitle})\n- [NOAA NHC](https://www.nhc.noaa.gov/)\n`;
}

async function fetchStormData(storm: StormEntry): Promise<StormMeta> {
  console.log(`  Fetching ${storm.fullName}...`);

  let summary: WikiSummary = {
    title: storm.fullName,
    description: storm.classification,
    extract: `${storm.fullName} was a ${storm.classification.toLowerCase()} during the ${storm.season} season.`,
  };

  try {
    const res = await fetch(`${WIKI_API}/${encodeURIComponent(storm.wikiTitle)}`, {
      headers: { "User-Agent": "StormTracker/1.0 (educational research)" },
    });
    if (res.ok) {
      summary = await res.json();
    }
  } catch {
    console.warn(`    Warning: Could not fetch summary for ${storm.wikiTitle}`);
  }

  const nums = extractNumbers(summary.extract || "");

  const sources = [
    { title: `Wikipedia — ${storm.fullName}`, url: `https://en.wikipedia.org/wiki/${storm.wikiTitle}`, type: "wiki" },
    { title: "NOAA National Hurricane Center", url: "https://www.nhc.noaa.gov/", type: "official" },
  ];

  const funFacts: string[] = [];
  if (storm.categorySaffir === 5) funFacts.push(`${storm.fullName} reached Category 5 intensity, the highest on the Saffir-Simpson scale.`);
  if (storm.basin === "WP") funFacts.push(`As a Western Pacific typhoon, ${storm.name} was named by the Japan Meteorological Agency.`);
  if (storm.year === 2005 && storm.basin === "NA") funFacts.push("The 2005 Atlantic hurricane season was one of the most active on record.");

  return {
    ...storm,
    summary: summary.extract?.slice(0, 500) || `${storm.fullName} was a notable ${storm.classification.toLowerCase()}.`,
    ogImageUrl: summary.originalimage?.source || summary.thumbnail?.source || null,
    peakWindKmh: nums.wind ?? null,
    peakPressure: nums.pressure ?? null,
    fatalities: nums.deaths ?? null,
    damageUsd: null,
    affectedAreas: [],
    sources,
    funFacts,
    researchMd: buildResearchMd(storm, summary, summary.extract || ""),
  };
}

function escapeSql(s: string): string {
  return s.replace(/'/g, "''");
}

function toSqlArray(arr: string[]): string {
  if (!arr.length) return "ARRAY[]::TEXT[]";
  return `ARRAY[${arr.map((s) => `'${escapeSql(s)}'`).join(", ")}]`;
}

async function main() {
  console.log(`\n🌀 Storm Library scraper — ${STORMS.length} storms\n`);

  const seedDir = join(process.cwd(), "supabase/seed");
  mkdirSync(seedDir, { recursive: true });

  const results: StormMeta[] = [];
  const sqlLines: string[] = [
    "-- 0002_seed_storms.sql — generated by scripts/fetch-wikipedia.ts",
    "-- Run in Supabase Dashboard → SQL Editor\n",
  ];

  for (const storm of STORMS) {
    const data = await fetchStormData(storm);
    results.push(data);

    const formedAt = `${data.year}-06-01`; // approximate
    const sql = `INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  '${escapeSql(data.slug)}', '${escapeSql(data.name)}', '${escapeSql(data.fullName)}',
  ${data.year}, '${escapeSql(data.season)}', '${data.basin}',
  ${data.categorySaffir ?? "NULL"}, '${escapeSql(data.classification)}',
  ${data.peakWindKmh ?? "NULL"}, ${data.peakPressure ?? "NULL"},
  '${formedAt}',
  ${data.fatalities ?? "NULL"}, ${data.damageUsd ?? "NULL"},
  ${toSqlArray(data.affectedAreas)},
  '${escapeSql(data.summary)}',
  '${escapeSql(data.researchMd)}',
  ${toSqlArray(data.funFacts)},
  '${escapeSql(JSON.stringify(data.sources))}'::JSONB,
  ${data.ogImageUrl ? `'${escapeSql(data.ogImageUrl)}'` : "NULL"},
  ${data.isFeatured ? "TRUE" : "FALSE"},
  ${data.displayOrder ?? "NULL"}
) ON CONFLICT (slug) DO NOTHING;`;

    sqlLines.push(sql);

    await sleep(500); // rate limit Wikipedia
  }

  // Write metadata JSON
  const metaPath = join(seedDir, "storms-meta.json");
  writeFileSync(metaPath, JSON.stringify(results, null, 2));
  console.log(`\n✅ storms-meta.json written → ${metaPath}`);

  // Write SQL seed migration
  const sqlPath = join(process.cwd(), "supabase/migrations/0002_seed_storms.sql");
  writeFileSync(sqlPath, sqlLines.join("\n\n"));
  console.log(`✅ 0002_seed_storms.sql written → ${sqlPath}`);
  console.log(`\n📋 Next step: Run the SQL in Supabase Dashboard → SQL Editor`);
}

main().catch(console.error);
