-- 0002_seed_storms.sql — generated by scripts/fetch-wikipedia.ts

-- Run in Supabase Dashboard → SQL Editor


INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-mitch-1998', 'Mitch', 'Hurricane Mitch',
  1998, '1998 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '1998-06-01',
  11374, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Mitch was an extremely powerful, deadly and catastrophic tropical cyclone in 1998 that caused 11,374 fatalities in Central America, becoming the second-deadliest Atlantic hurricane on record. It was the deadliest hurricane in Central American history, surpassing Hurricane Fifi–Orlene, which killed slightly fewer people in the same area in 1974. Mitch was the deadliest Atlantic hurricane in the satellite era, and the second-deadliest on record in the Atlantic, only behind the Great Hurr',
  '## Overview

Hurricane Mitch was an extremely powerful, deadly and catastrophic tropical cyclone in 1998 that caused 11,374 fatalities in Central America, becoming the second-deadliest Atlantic hurricane on record. It was the deadliest hurricane in Central American history, surpassing Hurricane Fifi–Orlene, which killed slightly fewer people in the same area in 1974. Mitch was the deadliest Atlantic hurricane in the satellite era, and the second-deadliest on record in the Atlantic, only behind the Great Hurricane of 1780, which killed at least 22,000 people.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Mitch)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Mitch reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Mitch","url":"https://en.wikipedia.org/wiki/Hurricane_Mitch","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/d/d8/Mitch_1998-10-26_1845Z.png',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-floyd-1999', 'Floyd', 'Hurricane Floyd',
  1999, '1999 Atlantic', 'NA',
  4, 'Hurricane',
  NULL, NULL,
  '1999-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Floyd was a powerful and destructive tropical cyclone which struck the Bahamas and the East Coast of the United States. It was the sixth named storm, fourth hurricane, and third major hurricane in the 1999 Atlantic hurricane season. Floyd triggered the fourth largest evacuation in US history when 2.6 million coastal residents of five states were ordered from their homes as it approached. The hurricane formed off the coast of Africa and lasted from September 7 to 19, becoming extratropi',
  '## Overview

Hurricane Floyd was a powerful and destructive tropical cyclone which struck the Bahamas and the East Coast of the United States. It was the sixth named storm, fourth hurricane, and third major hurricane in the 1999 Atlantic hurricane season. Floyd triggered the fourth largest evacuation in US history when 2.6 million coastal residents of five states were ordered from their homes as it approached. The hurricane formed off the coast of Africa and lasted from September 7 to 19, becoming extratropical after September 17, and peaked in strength as a very strong Category 4 hurricane. It was among the largest Atlantic hurricanes of its strength ever recorded, in terms of gale-force diameter.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Floyd)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Hurricane Floyd","url":"https://en.wikipedia.org/wiki/Hurricane_Floyd","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/b/b0/Floyd_1999-09-13_1215Z.png',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-isabel-2003', 'Isabel', 'Hurricane Isabel',
  2003, '2003 Atlantic', 'NA',
  5, 'Hurricane',
  266, NULL,
  '2003-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Isabel was a large and powerful Category 5 Atlantic hurricane that struck the east coast of the United States in September 2003. The ninth named storm, fifth hurricane, and second major hurricane of the season, Isabel formed in the eastern Atlantic Ocean on September 6 from a tropical wave. It moved northwestward through an area with light wind shear and warm waters, resulting in strengthening. Isabel reached peak winds of 165 mph (266 km/h) on September 11. After fluctuating in intens',
  '## Overview

Hurricane Isabel was a large and powerful Category 5 Atlantic hurricane that struck the east coast of the United States in September 2003. The ninth named storm, fifth hurricane, and second major hurricane of the season, Isabel formed in the eastern Atlantic Ocean on September 6 from a tropical wave. It moved northwestward through an area with light wind shear and warm waters, resulting in strengthening. Isabel reached peak winds of 165 mph (266 km/h) on September 11. After fluctuating in intensity for four days, Isabel gradually weakened and made landfall on the Outer Banks of North Carolina, with winds of 105 mph (169 km/h) on September 18, or a Category 2 on the Saffir-Simpson scale. Isabel quickly weakened over land and became extratropical over western Pennsylvania on the next day. On September 20, the extratropical remnants of Isabel were absorbed into another system over Eastern Canada.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Isabel)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Isabel reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Isabel","url":"https://en.wikipedia.org/wiki/Hurricane_Isabel","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Isabel_2003-09-11_1720Z.jpg/3840px-Isabel_2003-09-11_1720Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-charley-2004', 'Charley', 'Hurricane Charley',
  2004, '2004 Atlantic', 'NA',
  4, 'Hurricane',
  241, NULL,
  '2004-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Charley was the first of four separate hurricanes to impact or strike Florida during 2004, along with Frances, Ivan and Jeanne, as well as one of the strongest hurricanes ever to strike the United States. It was the third named storm, the second hurricane, and the second major hurricane of the 2004 Atlantic hurricane season. Charley lasted from August 9 to 15, and at its peak intensity it attained 150 mph (240 km/h) winds, making it a strong Category 4 hurricane on the Saffir–Simpson s',
  '## Overview

Hurricane Charley was the first of four separate hurricanes to impact or strike Florida during 2004, along with Frances, Ivan and Jeanne, as well as one of the strongest hurricanes ever to strike the United States. It was the third named storm, the second hurricane, and the second major hurricane of the 2004 Atlantic hurricane season. Charley lasted from August 9 to 15, and at its peak intensity it attained 150 mph (240 km/h) winds, making it a strong Category 4 hurricane on the Saffir–Simpson scale. It made landfall in Southwest Florida at maximum strength, becoming the strongest hurricane to hit the United States since Hurricane Andrew struck Florida in 1992 and tied with Hurricane Ian as the strongest hurricane to hit southwest Florida in recorded history.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Charley)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Hurricane Charley","url":"https://en.wikipedia.org/wiki/Hurricane_Charley","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/5/5c/Charley_2004-08-13_1945Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-ivan-2004', 'Ivan', 'Hurricane Ivan',
  2004, '2004 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2004-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Ivan was a large, long-lived, and devastating tropical cyclone that caused widespread damage in the Caribbean and United States. The ninth named storm, the sixth hurricane, and the fourth major hurricane of the active 2004 Atlantic hurricane season, Ivan formed in early September and reached Category 5 strength on the Saffir–Simpson Hurricane Scale (SSHS). Ivan caused catastrophic damage in Grenada as a strong Category 3 storm, heavy damage in Jamaica as a strong Category 4 storm, and ',
  '## Overview

Hurricane Ivan was a large, long-lived, and devastating tropical cyclone that caused widespread damage in the Caribbean and United States. The ninth named storm, the sixth hurricane, and the fourth major hurricane of the active 2004 Atlantic hurricane season, Ivan formed in early September and reached Category 5 strength on the Saffir–Simpson Hurricane Scale (SSHS). Ivan caused catastrophic damage in Grenada as a strong Category 3 storm, heavy damage in Jamaica as a strong Category 4 storm, and then severe damage in Grand Cayman, Cayman Islands, and the western tip of Cuba as a Category 5 hurricane. After peaking in strength, the hurricane moved north-northwest across the Gulf of Mexico to strike Pensacola/Milton, Florida and Alabama as a strong Category 3 storm, causing significant damage. Ivan dropped heavy rain on the Southeastern United States as it progressed northeastward and eastward through the Eastern United States, becoming an extratropical cyclone on September 18. The remnant low of the storm moved into the western subtropical Atlantic and regenerated into a tropical cyclone on September 22, which then moved across Florida and the Gulf of Mexico, and then into Louisiana and Texas, causing minimal damage. Ivan degenerated into a remnant low on September 24, before dissipating on the next day.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Ivan)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Ivan reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Ivan","url":"https://en.wikipedia.org/wiki/Hurricane_Ivan","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Ivan_2004-09-13_1900Z_%28alternate%29.jpg/3840px-Ivan_2004-09-13_1900Z_%28alternate%29.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-katrina-2005', 'Katrina', 'Hurricane Katrina',
  2005, '2005 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2005-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Katrina was an extremely powerful and catastrophic tropical cyclone that killed 1,392 people and caused damage estimated at $125 billion, particularly in and around the city of New Orleans, in late August 2005. It is tied with Hurricane Harvey as being the costliest tropical cyclone in the Atlantic basin. Katrina was the twelfth tropical cyclone, the fifth hurricane, the third major hurricane, and the second Category 5 hurricane of the 2005 Atlantic hurricane season. It was also the fo',
  '## Overview

Hurricane Katrina was an extremely powerful and catastrophic tropical cyclone that killed 1,392 people and caused damage estimated at $125 billion, particularly in and around the city of New Orleans, in late August 2005. It is tied with Hurricane Harvey as being the costliest tropical cyclone in the Atlantic basin. Katrina was the twelfth tropical cyclone, the fifth hurricane, the third major hurricane, and the second Category 5 hurricane of the 2005 Atlantic hurricane season. It was also the fourth-most intense Atlantic hurricane to make landfall in the contiguous United States, as measured by barometric pressure.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Katrina)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Katrina reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'The 2005 Atlantic hurricane season was one of the most active on record.'],
  '[{"title":"Wikipedia — Hurricane Katrina","url":"https://en.wikipedia.org/wiki/Hurricane_Katrina","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Katrina_2005-08-28_1700Z.jpg/3840px-Katrina_2005-08-28_1700Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  TRUE,
  1
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-rita-2005', 'Rita', 'Hurricane Rita',
  2005, '2005 Atlantic', 'NA',
  5, 'Hurricane',
  290, NULL,
  '2005-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Rita was the most intense tropical cyclone on record in the Gulf of Mexico, now tied with Hurricane Milton of 2024, as well as being one of the most intense Atlantic hurricanes on record overall. Part of the record-breaking 2005 Atlantic hurricane season, which included three of the ten most intense Atlantic hurricanes in terms of barometric pressure ever recorded, Rita was the seventeenth named storm, tenth hurricane, fifth major hurricane, and third Category 5 hurricane of the 2005 s',
  '## Overview

Hurricane Rita was the most intense tropical cyclone on record in the Gulf of Mexico, now tied with Hurricane Milton of 2024, as well as being one of the most intense Atlantic hurricanes on record overall. Part of the record-breaking 2005 Atlantic hurricane season, which included three of the ten most intense Atlantic hurricanes in terms of barometric pressure ever recorded, Rita was the seventeenth named storm, tenth hurricane, fifth major hurricane, and third Category 5 hurricane of the 2005 season. It was also the earliest-forming 17th named storm in the Atlantic until Tropical Storm Rene in 2020. Rita formed near The Bahamas from a tropical wave on September 18, 2005, that originally developed off the coast of West Africa. It moved westward, and after passing through the Florida Straits, Rita entered an environment of abnormally warm waters. Moving west-northwest, it rapidly intensified to reach peak winds of 180 mph (285 km/h), achieving Category 5 status on September 21. However, it weakened to a Category 3 hurricane before making landfall in Johnson''s Bayou, Louisiana, between Sabine Pass, Texas and Holly Beach, Louisiana, with winds of 115 mph (185 km/h). Rapidly weakening over land, Rita degenerated into a large low-pressure area over the lower Mississippi Valley by September 26.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Rita)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Rita reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'The 2005 Atlantic hurricane season was one of the most active on record.'],
  '[{"title":"Wikipedia — Hurricane Rita","url":"https://en.wikipedia.org/wiki/Hurricane_Rita","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Rita_2005-09-21_1915Z.jpg/3840px-Rita_2005-09-21_1915Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-wilma-2005', 'Wilma', 'Hurricane Wilma',
  2005, '2005 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2005-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Wilma was the most intense tropical cyclone in the Atlantic basin and the second-most intense tropical cyclone in the Western Hemisphere, both based on barometric pressure, after Hurricane Patricia in 2015. Wilma''s rapid intensification led to a 24-hour pressure drop of 97 mbar (2.9 inHg), setting a new basin record. At its peak, Hurricane Wilma''s eye contracted to a record minimum diameter of 2.3 mi (3.7 km). In the record-breaking 2005 Atlantic hurricane season, Wilma was the twenty-',
  '## Overview

Hurricane Wilma was the most intense tropical cyclone in the Atlantic basin and the second-most intense tropical cyclone in the Western Hemisphere, both based on barometric pressure, after Hurricane Patricia in 2015. Wilma''s rapid intensification led to a 24-hour pressure drop of 97 mbar (2.9 inHg), setting a new basin record. At its peak, Hurricane Wilma''s eye contracted to a record minimum diameter of 2.3 mi (3.7 km). In the record-breaking 2005 Atlantic hurricane season, Wilma was the twenty-second storm, thirteenth hurricane, sixth major hurricane, and fourth Category 5 hurricane, and was the second costliest hurricane in Mexican history, behind Hurricane Otis in 2023.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Wilma)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Wilma reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'The 2005 Atlantic hurricane season was one of the most active on record.'],
  '[{"title":"Wikipedia — Hurricane Wilma","url":"https://en.wikipedia.org/wiki/Hurricane_Wilma","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/2/24/Wilma_2005-10-19_1345Z.png',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-dean-2007', 'Dean', 'Hurricane Dean',
  2007, '2007 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2007-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Dean was the most powerful and destructive tropical cyclone of the 2007 Atlantic hurricane season. It ties with Hurricane Mitch for the tenth most intense Atlantic hurricane by atmospheric pressure. Additionally, it made the fifth most intense landfall in the basin by central pressure. A Cape Verde hurricane that formed on August 13, 2007, Dean took a west-northwest path from the eastern Atlantic Ocean through the Saint Lucia Channel and into the Caribbean Sea. It strengthened into a m',
  '## Overview

Hurricane Dean was the most powerful and destructive tropical cyclone of the 2007 Atlantic hurricane season. It ties with Hurricane Mitch for the tenth most intense Atlantic hurricane by atmospheric pressure. Additionally, it made the fifth most intense landfall in the basin by central pressure. A Cape Verde hurricane that formed on August 13, 2007, Dean took a west-northwest path from the eastern Atlantic Ocean through the Saint Lucia Channel and into the Caribbean Sea. It strengthened into a major hurricane, reaching Category 5 status on the Saffir–Simpson scale before passing just south of Jamaica on August 20. The storm made landfall on the Yucatán Peninsula on August 21 at peak intensity. It crossed the peninsula and emerged into the Bay of Campeche weakened, but still remained a hurricane. It strengthened briefly before making a second landfall near Tecolutla in the Mexican state of Veracruz on August 22. Dean drifted to the northwest, weakening into a remnant low which dissipated uneventfully over the southwestern United States. Dean was the second-most intense tropical cyclone worldwide of 2007 in terms of pressure, only behind Cyclone George in the Australian region, and tied with Felix as the most intense worldwide in terms of 1-minute sustained winds.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Dean_(2007))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Dean reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Dean","url":"https://en.wikipedia.org/wiki/Hurricane_Dean_(2007)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/2/2d/Dean_2007-08-21_0845Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-sandy-2012', 'Sandy', 'Hurricane Sandy',
  2012, '2012 Atlantic', 'NA',
  3, 'Hurricane',
  NULL, NULL,
  '2012-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Sandy was an extremely large and devastating tropical cyclone which ravaged the Caribbean and the coastal Mid-Atlantic region of the United States in late October 2012. It was the largest Atlantic hurricane on record as measured by diameter, with tropical-storm-force winds spanning 1,150 miles (1,850 km). The storm inflicted nearly US$70 billion in damage, and killed 254 people in eight countries, from the Caribbean to Canada. The eighteenth named storm, tenth hurricane, and second maj',
  '## Overview

Hurricane Sandy was an extremely large and devastating tropical cyclone which ravaged the Caribbean and the coastal Mid-Atlantic region of the United States in late October 2012. It was the largest Atlantic hurricane on record as measured by diameter, with tropical-storm-force winds spanning 1,150 miles (1,850 km). The storm inflicted nearly US$70 billion in damage, and killed 254 people in eight countries, from the Caribbean to Canada. The eighteenth named storm, tenth hurricane, and second major hurricane of the 2012 Atlantic hurricane season, Sandy was a Category 3 storm at its peak intensity when it made landfall in Cuba, though most of the damage it caused was after it became a Category 1–equivalent extratropical cyclone off the coast of the Northeastern United States.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Sandy)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Hurricane Sandy","url":"https://en.wikipedia.org/wiki/Hurricane_Sandy","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/4/45/Sandy_2012-10-25_0320Z_%28cropped%29.png',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-matthew-2016', 'Matthew', 'Hurricane Matthew',
  2016, '2016 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2016-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Matthew was a powerful and devastating tropical cyclone which caused catastrophic damage and a humanitarian crisis in Haiti, as well as widespread devastation across Cuba, the Bahamas, and the southeastern United States. The deadliest Atlantic hurricane since Hurricane Stan in 2005, and the first Category 5 Atlantic hurricane since Felix in 2007, Matthew was the thirteenth named storm, fifth hurricane and second major hurricane of the 2016 Atlantic hurricane season. It caused extensive',
  '## Overview

Hurricane Matthew was a powerful and devastating tropical cyclone which caused catastrophic damage and a humanitarian crisis in Haiti, as well as widespread devastation across Cuba, the Bahamas, and the southeastern United States. The deadliest Atlantic hurricane since Hurricane Stan in 2005, and the first Category 5 Atlantic hurricane since Felix in 2007, Matthew was the thirteenth named storm, fifth hurricane and second major hurricane of the 2016 Atlantic hurricane season. It caused extensive damage to landmasses in the Greater Antilles, and severe damage in several islands of the Bahamas which were still recovering from Joaquin, which had pounded the archipelago nearly a year earlier. Matthew also approached the southeastern United States, but stayed just offshore, paralleling the Florida coastline.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Matthew)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Matthew reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Matthew","url":"https://en.wikipedia.org/wiki/Hurricane_Matthew","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/1/12/Matthew_2016-10-01_0225Z.png',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-harvey-2017', 'Harvey', 'Hurricane Harvey',
  2017, '2017 Atlantic', 'NA',
  4, 'Hurricane',
  NULL, NULL,
  '2017-06-01',
  100, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Harvey was a powerful and devastating tropical cyclone that made landfall in Texas and Louisiana in August 2017, causing catastrophic flooding and more than 100 deaths. It is tied with 2005''s Hurricane Katrina as the costliest tropical cyclone on record, inflicting $125 billion in damage, primarily from catastrophic rainfall-triggered flooding in Greater Houston and Southeast Texas; this made the storm the costliest natural disaster recorded in Texas at the time. It was the first major',
  '## Overview

Hurricane Harvey was a powerful and devastating tropical cyclone that made landfall in Texas and Louisiana in August 2017, causing catastrophic flooding and more than 100 deaths. It is tied with 2005''s Hurricane Katrina as the costliest tropical cyclone on record, inflicting $125 billion in damage, primarily from catastrophic rainfall-triggered flooding in Greater Houston and Southeast Texas; this made the storm the costliest natural disaster recorded in Texas at the time. It was the first major hurricane to make landfall in the United States since Wilma in 2005, ending a record 12-year span. In a four-day period, many areas received more than 40 inches (1,000 mm) of rain as the system slowly meandered over eastern Texas and adjacent waters, causing unprecedented flooding. With peak accumulations of 60.58 in (1,539 mm) in Nederland, Texas, Harvey was the wettest tropical cyclone on record in the United States. The resulting floods inundated hundreds of thousands of homes, which displaced more than 30,000 people and prompted more than 17,000 rescues.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Harvey)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Hurricane Harvey","url":"https://en.wikipedia.org/wiki/Hurricane_Harvey","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/a/a5/Harvey_2017-08-25_2337Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-irma-2017', 'Irma', 'Hurricane Irma',
  2017, '2017 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2017-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Irma was an extremely powerful and devastating tropical cyclone that caused extensive damage and multiple deaths across the Antilles and Eastern United States in September 2017. Irma was the first Category 5 hurricane to strike the Leeward Islands on record, though it was followed by Hurricane Maria, which struck the region at Category 5 intensity as well two weeks later. At the time, Irma was considered the most powerful hurricane on record in the open Atlantic region, outside of the ',
  '## Overview

Hurricane Irma was an extremely powerful and devastating tropical cyclone that caused extensive damage and multiple deaths across the Antilles and Eastern United States in September 2017. Irma was the first Category 5 hurricane to strike the Leeward Islands on record, though it was followed by Hurricane Maria, which struck the region at Category 5 intensity as well two weeks later. At the time, Irma was considered the most powerful hurricane on record in the open Atlantic region, outside of the Caribbean Sea and Gulf of Mexico, until it was surpassed by Hurricane Dorian two years later. It was also the third-strongest Atlantic hurricane at landfall ever recorded, just behind the 1935 Labor Day hurricane, Hurricane Melissa, and Dorian.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Irma)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Irma reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Irma","url":"https://en.wikipedia.org/wiki/Hurricane_Irma","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/2/2d/Irma_2017-09-06_1230Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-maria-2017', 'Maria', 'Hurricane Maria',
  2017, '2017 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2017-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Maria was a hurricane during the 2017 Atlantic season.',
  '## Overview

Hurricane Maria was a hurricane during the 2017 Atlantic season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Maria)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Maria reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Maria","url":"https://en.wikipedia.org/wiki/Hurricane_Maria","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-michael-2018', 'Michael', 'Hurricane Michael',
  2018, '2018 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2018-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Michael was a hurricane during the 2018 Atlantic season.',
  '## Overview

Hurricane Michael was a hurricane during the 2018 Atlantic season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Michael_(2018))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Michael reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Michael","url":"https://en.wikipedia.org/wiki/Hurricane_Michael_(2018)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-dorian-2019', 'Dorian', 'Hurricane Dorian',
  2019, '2019 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2019-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Dorian was a hurricane during the 2019 Atlantic season.',
  '## Overview

Hurricane Dorian was a hurricane during the 2019 Atlantic season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Dorian)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Dorian reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Dorian","url":"https://en.wikipedia.org/wiki/Hurricane_Dorian","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-ian-2022', 'Ian', 'Hurricane Ian',
  2022, '2022 Atlantic', 'NA',
  5, 'Hurricane',
  NULL, NULL,
  '2022-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Ian was a hurricane during the 2022 Atlantic season.',
  '## Overview

Hurricane Ian was a hurricane during the 2022 Atlantic season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Ian_(2022))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Ian reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Ian","url":"https://en.wikipedia.org/wiki/Hurricane_Ian_(2022)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-otis-2023', 'Otis', 'Hurricane Otis',
  2023, '2023 Pacific', 'EP',
  5, 'Hurricane',
  NULL, NULL,
  '2023-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Otis was a hurricane during the 2023 Pacific season.',
  '## Overview

Hurricane Otis was a hurricane during the 2023 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Otis)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Otis reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Otis","url":"https://en.wikipedia.org/wiki/Hurricane_Otis","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-linda-1997', 'Linda', 'Typhoon Linda',
  1997, '1997 Pacific', 'WP',
  NULL, 'Typhoon',
  NULL, NULL,
  '1997-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Linda was a typhoon during the 1997 Pacific season.',
  '## Overview

Typhoon Linda was a typhoon during the 1997 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Tropical_Storm_Linda_(1997))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['As a Western Pacific typhoon, Linda was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Linda","url":"https://en.wikipedia.org/wiki/Tropical_Storm_Linda_(1997)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-saomai-2000', 'Saomai', 'Typhoon Saomai',
  2000, '2000 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2000-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Saomai was a typhoon during the 2000 Pacific season.',
  '## Overview

Typhoon Saomai was a typhoon during the 2000 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Saomai_(2000))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Saomai reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Saomai was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Saomai","url":"https://en.wikipedia.org/wiki/Typhoon_Saomai_(2000)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-xangsane-2006', 'Xangsane', 'Typhoon Xangsane',
  2006, '2006 Pacific', 'WP',
  4, 'Typhoon',
  NULL, NULL,
  '2006-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Xangsane, known in the Philippines as Typhoon Milenyo, was a strong and deadly typhoon that affected the Philippines, and Indochina during the 2006 Pacific typhoon season.',
  '## Overview

Typhoon Xangsane, known in the Philippines as Typhoon Milenyo, was a strong and deadly typhoon that affected the Philippines, and Indochina during the 2006 Pacific typhoon season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Xangsane)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['As a Western Pacific typhoon, Xangsane was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Xangsane","url":"https://en.wikipedia.org/wiki/Typhoon_Xangsane","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Xangsane_2006-09-27_0500Z.jpg/3840px-Xangsane_2006-09-27_0500Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-durian-2006', 'Durian', 'Typhoon Durian',
  2006, '2006 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2006-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Durian was a typhoon during the 2006 Pacific season.',
  '## Overview

Typhoon Durian was a typhoon during the 2006 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Durian)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Durian reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Durian was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Durian","url":"https://en.wikipedia.org/wiki/Typhoon_Durian","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-ketsana-2009', 'Ketsana', 'Typhoon Ketsana',
  2009, '2009 Pacific', 'WP',
  2, 'Typhoon',
  NULL, NULL,
  '2009-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Ketsana was a typhoon during the 2009 Pacific season.',
  '## Overview

Typhoon Ketsana was a typhoon during the 2009 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Ketsana)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['As a Western Pacific typhoon, Ketsana was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Ketsana","url":"https://en.wikipedia.org/wiki/Typhoon_Ketsana","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-megi-2010', 'Megi', 'Typhoon Megi',
  2010, '2010 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2010-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Megi was a typhoon during the 2010 Pacific season.',
  '## Overview

Typhoon Megi was a typhoon during the 2010 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Megi_(2010))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Megi reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Megi was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Megi","url":"https://en.wikipedia.org/wiki/Typhoon_Megi_(2010)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-bopha-2012', 'Bopha', 'Typhoon Bopha',
  2012, '2012 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2012-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Bopha was a typhoon during the 2012 Pacific season.',
  '## Overview

Typhoon Bopha was a typhoon during the 2012 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Bopha)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Bopha reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Bopha was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Bopha","url":"https://en.wikipedia.org/wiki/Typhoon_Bopha","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-haiyan-2013', 'Haiyan', 'Typhoon Haiyan',
  2013, '2013 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2013-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Haiyan, known in the Philippines as Super Typhoon Yolanda, was an extremely powerful and catastrophic tropical cyclone that is among the most intense tropical cyclones ever recorded. Upon making landfall, Haiyan devastated portions of Southeast Asia, particularly the Philippines, during early November 2013. It is one of the deadliest typhoons on record in the Philippines, killing at least 6,300 people in the region of Visayas alone. It was the most intense and deadliest tropical cyclone ',
  '## Overview

Typhoon Haiyan, known in the Philippines as Super Typhoon Yolanda, was an extremely powerful and catastrophic tropical cyclone that is among the most intense tropical cyclones ever recorded. Upon making landfall, Haiyan devastated portions of Southeast Asia, particularly the Philippines, during early November 2013. It is one of the deadliest typhoons on record in the Philippines, killing at least 6,300 people in the region of Visayas alone. It was the most intense and deadliest tropical cyclone worldwide in 2013.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Haiyan)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Haiyan reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Haiyan was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Haiyan","url":"https://en.wikipedia.org/wiki/Typhoon_Haiyan","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/6/67/Haiyan_2013-11-07_1345Z_%28alternate%2C_borderless%29.png',
  TRUE,
  2
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-damrey-2017', 'Damrey', 'Typhoon Damrey',
  2017, '2017 Pacific', 'WP',
  2, 'Typhoon',
  NULL, NULL,
  '2017-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Damrey, known in the Philippines as Severe Tropical Storm Ramil, was a strong tropical cyclone that affected the Philippines and Vietnam during early November 2017. Damrey first originated as a tropical depression over the Philippine archipelago of Visayas on October 31. Emerging into the South China Sea a few days later, the system strengthened into the second deadliest and twenty-third named storm of the 2017 Pacific typhoon season. Rapidly intensifying, Damrey became the season''s tent',
  '## Overview

Typhoon Damrey, known in the Philippines as Severe Tropical Storm Ramil, was a strong tropical cyclone that affected the Philippines and Vietnam during early November 2017. Damrey first originated as a tropical depression over the Philippine archipelago of Visayas on October 31. Emerging into the South China Sea a few days later, the system strengthened into the second deadliest and twenty-third named storm of the 2017 Pacific typhoon season. Rapidly intensifying, Damrey became the season''s tenth typhoon on November 3, reaching its peak intensity as a Category 2 on the same day. Damrey made landfall over Khánh Hoà, Vietnam on November 4 and began to rapidly weaken, fully dissipating on November 5.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Damrey_(2017))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['As a Western Pacific typhoon, Damrey was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Damrey","url":"https://en.wikipedia.org/wiki/Typhoon_Damrey_(2017)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/3/3b/Damrey_2017-11-03_0507Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-mangkhut-2018', 'Mangkhut', 'Typhoon Mangkhut',
  2018, '2018 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2018-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Mangkhut was a typhoon during the 2018 Pacific season.',
  '## Overview

Typhoon Mangkhut was a typhoon during the 2018 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Mangkhut)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Mangkhut reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Mangkhut was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Mangkhut","url":"https://en.wikipedia.org/wiki/Typhoon_Mangkhut","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-goni-2020', 'Goni', 'Typhoon Goni',
  2020, '2020 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2020-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Goni was a typhoon during the 2020 Pacific season.',
  '## Overview

Typhoon Goni was a typhoon during the 2020 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Goni)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Goni reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Goni was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Goni","url":"https://en.wikipedia.org/wiki/Typhoon_Goni","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-rai-2021', 'Rai', 'Typhoon Rai',
  2021, '2021 Pacific', 'WP',
  5, 'Typhoon',
  193, NULL,
  '2021-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Rai, also named Odette locally, was the second-costliest tropical cyclone in the Philippines after it struck the country in December 2021. The typhoon also killed 409 people in the Philippines, with the greatest deaths in Bohol province. Rai formed on December 11 in the western Pacific Ocean. Two days later, it strengthened into a tropical storm. After passing near Palau, Rai entered the Philippine Area of Responsibility (PAR) by the night of December 14, where PAGASA named it Odette. Ra',
  '## Overview

Typhoon Rai, also named Odette locally, was the second-costliest tropical cyclone in the Philippines after it struck the country in December 2021. The typhoon also killed 409 people in the Philippines, with the greatest deaths in Bohol province. Rai formed on December 11 in the western Pacific Ocean. Two days later, it strengthened into a tropical storm. After passing near Palau, Rai entered the Philippine Area of Responsibility (PAR) by the night of December 14, where PAGASA named it Odette. Rai attained typhoon status and rapidly intensified while approaching the Philippines. The American-based Joint Typhoon Warning Center (JTWC) designated Rai as a super typhoon. Around that time, the JMA estimated peak maximum sustained winds of 195 km/h (120 mph). On December 16, the typhoon traversed the Visayas in the central Philippines, exiting into the Sulu Sea. After making its last landfall over Palawan, Rai continued to weaken before unexpectedly re-intensifying into a Category 5-equivalent typhoon by December 18, while nearing Vietnam. On the next day, Rai entered yet another weakening phase, dissipating on December 21, southeast of Hong Kong.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Rai)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Rai reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Rai was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Rai","url":"https://en.wikipedia.org/wiki/Typhoon_Rai","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Rai_2021-12-16_0159Z.jpg/3840px-Rai_2021-12-16_0159Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-noru-2022', 'Noru', 'Typhoon Noru',
  2022, '2022 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2022-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Noru, known in the Philippines as Super Typhoon Karding, was a powerful and destructive tropical cyclone that affected Indochina and the Philippines in late September 2022 — where it caused widespread agricultural damage. Noru was the sixteenth named storm and eighth typhoon, and third super typhoon of the 2022 Pacific typhoon season, Noru originated from a disturbance over the Philippine Sea, slowly tracking eastward until its development into a tropical depression, where it began to mo',
  '## Overview

Typhoon Noru, known in the Philippines as Super Typhoon Karding, was a powerful and destructive tropical cyclone that affected Indochina and the Philippines in late September 2022 — where it caused widespread agricultural damage. Noru was the sixteenth named storm and eighth typhoon, and third super typhoon of the 2022 Pacific typhoon season, Noru originated from a disturbance over the Philippine Sea, slowly tracking eastward until its development into a tropical depression, where it began to move westward.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Noru_(2022))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Noru reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Noru was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Noru","url":"https://en.wikipedia.org/wiki/Typhoon_Noru_(2022)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/0/08/Noru_2022-09-24_2330Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-doksuri-2023', 'Doksuri', 'Typhoon Doksuri',
  2023, '2023 Pacific', 'WP',
  4, 'Typhoon',
  NULL, NULL,
  '2023-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Doksuri, known in the Philippines as Super Typhoon Egay, was a powerful and highly destructive tropical cyclone which became the costliest typhoon to hit China, the costliest tropical cyclone outside of the North Atlantic, and the costliest typhoon on record, breaking the previous record of Typhoon Mireille in 1991. Doksuri was also the strongest typhoon to impact Fujian since Typhoon Meranti in 2016, and the most powerful typhoon to strike the province since records began in 1950. Aside',
  '## Overview

Typhoon Doksuri, known in the Philippines as Super Typhoon Egay, was a powerful and highly destructive tropical cyclone which became the costliest typhoon to hit China, the costliest tropical cyclone outside of the North Atlantic, and the costliest typhoon on record, breaking the previous record of Typhoon Mireille in 1991. Doksuri was also the strongest typhoon to impact Fujian since Typhoon Meranti in 2016, and the most powerful typhoon to strike the province since records began in 1950. Aside from China, Doksuri also caused extensive damage in the Philippines, Taiwan, and Vietnam, in late July 2023.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Doksuri)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['As a Western Pacific typhoon, Doksuri was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Doksuri","url":"https://en.wikipedia.org/wiki/Typhoon_Doksuri","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/f/fc/Doksuri_2023-07-25_0430Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'typhoon-yagi-2024', 'Yagi', 'Typhoon Yagi',
  2024, '2024 Pacific', 'WP',
  5, 'Typhoon',
  NULL, NULL,
  '2024-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Typhoon Yagi was a powerful and significant tropical cyclone which caused extensive damage in Southeast Asia and South China in early September 2024. Known in the Philippines as Severe Tropical Storm Enteng and in Vietnam as Typhoon No. 3 of 2024, Yagi is the eleventh named storm, the first violent typhoon, and the first super typhoon of the 2024 Pacific typhoon season. Additionally, it is the strongest typhoon in 70 years to strike Vietnam according to the country''s government, the strongest ty',
  '## Overview

Typhoon Yagi was a powerful and significant tropical cyclone which caused extensive damage in Southeast Asia and South China in early September 2024. Known in the Philippines as Severe Tropical Storm Enteng and in Vietnam as Typhoon No. 3 of 2024, Yagi is the eleventh named storm, the first violent typhoon, and the first super typhoon of the 2024 Pacific typhoon season. Additionally, it is the strongest typhoon in 70 years to strike Vietnam according to the country''s government, the strongest typhoon to strike China during the meteorological autumn, and one of the four Category 5-equivalent super typhoons recorded in the South China Sea. Yagi is also the second most intense tropical cyclones worldwide in 2024, behind Hurricane Milton in the Atlantic.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Typhoon_Yagi)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Typhoon Yagi reached Category 5 intensity, the highest on the Saffir-Simpson scale.', 'As a Western Pacific typhoon, Yagi was named by the Japan Meteorological Agency.'],
  '[{"title":"Wikipedia — Typhoon Yagi","url":"https://en.wikipedia.org/wiki/Typhoon_Yagi","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/7/7c/Yagi_2024-09-05_0000Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-linda-1997', 'Linda', 'Hurricane Linda',
  1997, '1997 Pacific', 'EP',
  5, 'Hurricane',
  298, NULL,
  '1997-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Linda was an extremely powerful tropical cyclone that was, at the time, the most intense eastern Pacific hurricane on record, until it was surpassed 18 years later by Patricia. Forming from a tropical wave on September 9, 1997, Linda steadily intensified and reached hurricane status within 36 hours of developing. The storm rapidly intensified, reaching sustained winds of 185 mph (295 km/h) and an estimated central pressure of 902 millibars (26.6 inHg); both were records for the eastern',
  '## Overview

Hurricane Linda was an extremely powerful tropical cyclone that was, at the time, the most intense eastern Pacific hurricane on record, until it was surpassed 18 years later by Patricia. Forming from a tropical wave on September 9, 1997, Linda steadily intensified and reached hurricane status within 36 hours of developing. The storm rapidly intensified, reaching sustained winds of 185 mph (295 km/h) and an estimated central pressure of 902 millibars (26.6 inHg); both were records for the eastern Pacific until Hurricane Patricia surpassed them in 2015. The hurricane was briefly forecast to move toward southern California, but instead, it turned out to sea and lost its status as a tropical cyclone on September 17, before dissipating on September 21. Linda was the fifteenth tropical cyclone, thirteenth named storm, seventh hurricane, and fifth major hurricane of the 1997 Pacific hurricane season. Linda was also the most intense tropical cyclone worldwide in 1997.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Linda_(1997))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Linda reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Linda","url":"https://en.wikipedia.org/wiki/Hurricane_Linda_(1997)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Linda_1997-09-12_1700Z.jpg/3840px-Linda_1997-09-12_1700Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-kenna-2002', 'Kenna', 'Hurricane Kenna',
  2002, '2002 Pacific', 'EP',
  5, 'Hurricane',
  266, NULL,
  '2002-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Kenna was the fourth-most intense tropical cyclone on record in the Eastern Pacific basin, and at the time the third-most intense Pacific hurricane to strike the coast of Mexico. Kenna was the sixteenth tropical depression, thirteenth tropical storm, seventh hurricane, sixth major hurricane, and third Category 5 hurricane of the 2002 Pacific hurricane season. After forming on October 22 to the south of Mexico from a tropical wave, forecasters consistently predicted the storm to strengt',
  '## Overview

Hurricane Kenna was the fourth-most intense tropical cyclone on record in the Eastern Pacific basin, and at the time the third-most intense Pacific hurricane to strike the coast of Mexico. Kenna was the sixteenth tropical depression, thirteenth tropical storm, seventh hurricane, sixth major hurricane, and third Category 5 hurricane of the 2002 Pacific hurricane season. After forming on October 22 to the south of Mexico from a tropical wave, forecasters consistently predicted the storm to strengthen much less than it actually did. Moving into an area of favorable upper-level conditions and warm sea surface temperatures, Kenna quickly strengthened to reach peak winds of 165 mph (270 km/h) as a Category 5 hurricane, on October 25, while located about 255 mi (410 km) southwest of Puerto Vallarta, Jalisco. Weakening as it turned to the northeast, the hurricane made landfall near San Blas, Nayarit as a Category 4 hurricane, with sustained winds of 140 mph (220 km/h), before dissipating on October 26 over the Sierra Madre Occidental mountains.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Kenna)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Kenna reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Kenna","url":"https://en.wikipedia.org/wiki/Hurricane_Kenna","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hurricane_Kenna_24_oct_2002_1750Z.jpg/3840px-Hurricane_Kenna_24_oct_2002_1750Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-patricia-2015', 'Patricia', 'Hurricane Patricia',
  2015, '2015 Pacific', 'EP',
  5, 'Hurricane',
  346, 872,
  '2015-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Patricia was the most powerful tropical cyclone on record worldwide in terms of maximum sustained winds. It was also the second-most intense on record worldwide in terms of pressure, with a minimum atmospheric pressure of 872 mbar, just behind Typhoon Tip''s 870 mbar. Originating from a sprawling disturbance near the Gulf of Tehuantepec, south of Mexico, in mid-October 2015, Patricia was first classified as a tropical depression on October 20. Initial development was slow, with only mod',
  '## Overview

Hurricane Patricia was the most powerful tropical cyclone on record worldwide in terms of maximum sustained winds. It was also the second-most intense on record worldwide in terms of pressure, with a minimum atmospheric pressure of 872 mbar, just behind Typhoon Tip''s 870 mbar. Originating from a sprawling disturbance near the Gulf of Tehuantepec, south of Mexico, in mid-October 2015, Patricia was first classified as a tropical depression on October 20. Initial development was slow, with only modest strengthening within the first day of its classification. The system later became a tropical storm and was named Patricia, the twenty-fourth named storm of the 2015 Pacific hurricane season. Exceptionally favorable environmental conditions fueled explosive intensification on October 22. A well-defined eye developed within an intense central dense overcast and Patricia grew from a tropical storm to a Category 5 hurricane in just 24 hours—a near-record pace. On October 23, the hurricane achieved its record peak intensity with maximum sustained winds of 215 mph (345 km/h). This made it the most intense tropical cyclone on record in the Western Hemisphere and the strongest globally in terms of one-minute maximum sustained winds.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Patricia)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Patricia reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Patricia","url":"https://en.wikipedia.org/wiki/Hurricane_Patricia","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Patricia_2015-10-23_1730Z.jpg/3840px-Patricia_2015-10-23_1730Z.jpg',
  TRUE,
  3
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-willa-2018', 'Willa', 'Hurricane Willa',
  2018, '2018 Pacific', 'EP',
  5, 'Hurricane',
  NULL, NULL,
  '2018-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Willa was a powerful tropical cyclone that brought torrential rains and destructive winds to southwestern Mexico, particularly the states of Sinaloa and Nayarit, during late October 2018. It was the twenty-fifth tropical cyclone, twenty-second named storm, thirteenth hurricane, tenth major hurricane, and record-tying third Category 5 hurricane of the 2018 Pacific hurricane season. Willa was the first major hurricane to make landfall in the Mexican state of Sinaloa since Lane in 2006.',
  '## Overview

Hurricane Willa was a powerful tropical cyclone that brought torrential rains and destructive winds to southwestern Mexico, particularly the states of Sinaloa and Nayarit, during late October 2018. It was the twenty-fifth tropical cyclone, twenty-second named storm, thirteenth hurricane, tenth major hurricane, and record-tying third Category 5 hurricane of the 2018 Pacific hurricane season. Willa was the first major hurricane to make landfall in the Mexican state of Sinaloa since Lane in 2006.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Willa)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Hurricane Willa reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Hurricane Willa","url":"https://en.wikipedia.org/wiki/Hurricane_Willa","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/6/67/Willa_2018-10-22_0850Z.jpg',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'hurricane-hilary-2023', 'Hilary', 'Hurricane Hilary',
  2023, '2023 Pacific', 'EP',
  4, 'Hurricane',
  225, 940,
  '2023-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Hurricane Hilary was a large and intense Pacific hurricane in August 2023 that brought torrential rainfall and gusty winds to the Pacific Coast of Mexico along the Baja California peninsula, and the Southwestern United States, resulting in widespread flooding and mudslides to the region. The hurricane was the eighth named storm, sixth hurricane, and fourth major hurricane of the active and highly destructive 2023 Pacific hurricane season. Hilary originated from a tropical wave south of Mexico on',
  '## Overview

Hurricane Hilary was a large and intense Pacific hurricane in August 2023 that brought torrential rainfall and gusty winds to the Pacific Coast of Mexico along the Baja California peninsula, and the Southwestern United States, resulting in widespread flooding and mudslides to the region. The hurricane was the eighth named storm, sixth hurricane, and fourth major hurricane of the active and highly destructive 2023 Pacific hurricane season. Hilary originated from a tropical wave south of Mexico on August 16, and strengthened into a hurricane a day later while paralleling the southwest coast of Mexico. The system underwent rapid intensification, reaching maximum sustained winds of 140 mph (220 km/h) and a central pressure of 940 mbar (27.76 inHg) on August 18, making it a Category 4 on the Saffir-Simpson scale. After environmental conditions became unfavorable, Hilary weakened as it approached land, making landfall on August 20 as a tropical storm in San Quintín along the western Baja California peninsula. Hilary became a post-tropical cyclone over land, before being absorbed into a new non-tropical low-pressure area early on August 21.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Hurricane_Hilary_(2023))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Hurricane Hilary","url":"https://en.wikipedia.org/wiki/Hurricane_Hilary_(2023)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/3/31/Hilary_2023-08-18_0930Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-nargis-2008', 'Nargis', 'Cyclone Nargis',
  2008, '2008 Indian', 'NI',
  4, 'Cyclone',
  NULL, NULL,
  '2008-06-01',
  138373, NULL,
  ARRAY[]::TEXT[],
  'Extremely Severe Cyclonic Storm Nargis was an extremely deadly and catastrophic tropical cyclone that caused the worst natural disaster in the recorded history of Myanmar during early May 2008. The cyclone made landfall in Myanmar on 2 May 2008, sending a storm surge 40 kilometres up the densely populated Irrawaddy delta, causing catastrophic destruction and at least 138,373 fatalities. The Labutta Township alone was reported to have 80,000 dead, with about 10,000 more deaths in Bogale. There we',
  '## Overview

Extremely Severe Cyclonic Storm Nargis was an extremely deadly and catastrophic tropical cyclone that caused the worst natural disaster in the recorded history of Myanmar during early May 2008. The cyclone made landfall in Myanmar on 2 May 2008, sending a storm surge 40 kilometres up the densely populated Irrawaddy delta, causing catastrophic destruction and at least 138,373 fatalities. The Labutta Township alone was reported to have 80,000 dead, with about 10,000 more deaths in Bogale. There were around 55,000 people missing and many other deaths were found in other towns and areas, although the Myanmar government''s official death toll may have been under-reported, and there have been allegations that government officials stopped updating the death toll after 138,000 to minimise political fallout. The feared ''second wave'' of fatalities from disease and lack of relief efforts never materialised. Damage was at 13 trillion kyat (US$15.3 billion), making Nargis the costliest tropical cyclone on record in the North Indian Ocean at the time, before that record was broken by Amphan in 2020.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Nargis)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Nargis","url":"https://en.wikipedia.org/wiki/Cyclone_Nargis","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Nargis_2008-05-02_0645Z.jpg/3840px-Nargis_2008-05-02_0645Z.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-phailin-2013', 'Phailin', 'Cyclone Phailin',
  2013, '2013 Indian', 'NI',
  4, 'Cyclone',
  NULL, NULL,
  '2013-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Phailin was a cyclone during the 2013 Indian season.',
  '## Overview

Cyclone Phailin was a cyclone during the 2013 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Phailin)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Phailin","url":"https://en.wikipedia.org/wiki/Cyclone_Phailin","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-fani-2019', 'Fani', 'Cyclone Fani',
  2019, '2019 Indian', 'NI',
  4, 'Cyclone',
  NULL, NULL,
  '2019-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Fani was a cyclone during the 2019 Indian season.',
  '## Overview

Cyclone Fani was a cyclone during the 2019 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Fani)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Fani","url":"https://en.wikipedia.org/wiki/Cyclone_Fani","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-amphan-2020', 'Amphan', 'Cyclone Amphan',
  2020, '2020 Indian', 'NI',
  5, 'Cyclone',
  NULL, NULL,
  '2020-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Amphan was a cyclone during the 2020 Indian season.',
  '## Overview

Cyclone Amphan was a cyclone during the 2020 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Amphan)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Amphan reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Amphan","url":"https://en.wikipedia.org/wiki/Cyclone_Amphan","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-gafilo-2004', 'Gafilo', 'Cyclone Gafilo',
  2004, '2004 Indian', 'SI',
  5, 'Cyclone',
  NULL, NULL,
  '2004-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Gafilo was a cyclone during the 2004 Indian season.',
  '## Overview

Cyclone Gafilo was a cyclone during the 2004 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Gafilo)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Gafilo reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Gafilo","url":"https://en.wikipedia.org/wiki/Cyclone_Gafilo","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-idai-2019', 'Idai', 'Cyclone Idai',
  2019, '2019 Indian', 'SI',
  4, 'Cyclone',
  NULL, NULL,
  '2019-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Idai was a cyclone during the 2019 Indian season.',
  '## Overview

Cyclone Idai was a cyclone during the 2019 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Idai)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Idai","url":"https://en.wikipedia.org/wiki/Cyclone_Idai","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-kenneth-2019', 'Kenneth', 'Cyclone Kenneth',
  2019, '2019 Indian', 'SI',
  4, 'Cyclone',
  NULL, NULL,
  '2019-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Kenneth was a cyclone during the 2019 Indian season.',
  '## Overview

Cyclone Kenneth was a cyclone during the 2019 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Kenneth)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Kenneth","url":"https://en.wikipedia.org/wiki/Cyclone_Kenneth","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-freddy-2023', 'Freddy', 'Cyclone Freddy',
  2023, '2023 Indian', 'SI',
  5, 'Cyclone',
  NULL, NULL,
  '2023-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Freddy was a cyclone during the 2023 Indian season.',
  '## Overview

Cyclone Freddy was a cyclone during the 2023 Indian season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Freddy)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Freddy reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Freddy","url":"https://en.wikipedia.org/wiki/Cyclone_Freddy","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-pam-2015', 'Pam', 'Cyclone Pam',
  2015, '2015 Pacific', 'SP',
  5, 'Cyclone',
  NULL, NULL,
  '2015-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Pam was a cyclone during the 2015 Pacific season.',
  '## Overview

Cyclone Pam was a cyclone during the 2015 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Pam)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Pam reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Pam","url":"https://en.wikipedia.org/wiki/Cyclone_Pam","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-winston-2016', 'Winston', 'Cyclone Winston',
  2016, '2016 Pacific', 'SP',
  5, 'Cyclone',
  NULL, NULL,
  '2016-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Winston was a cyclone during the 2016 Pacific season.',
  '## Overview

Cyclone Winston was a cyclone during the 2016 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Winston)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Winston reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Winston","url":"https://en.wikipedia.org/wiki/Cyclone_Winston","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-harold-2020', 'Harold', 'Cyclone Harold',
  2020, '2020 Pacific', 'SP',
  5, 'Cyclone',
  NULL, NULL,
  '2020-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Harold was a cyclone during the 2020 Pacific season.',
  '## Overview

Cyclone Harold was a cyclone during the 2020 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Harold)
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY['Cyclone Harold reached Category 5 intensity, the highest on the Saffir-Simpson scale.'],
  '[{"title":"Wikipedia — Cyclone Harold","url":"https://en.wikipedia.org/wiki/Cyclone_Harold","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storms (
  slug, name, full_name, year, season, basin,
  category_saffir, classification,
  peak_wind_kmh, peak_pressure,
  formed_at,
  fatalities, damage_usd,
  affected_areas, summary, research_md, fun_facts, sources,
  og_image_url, is_featured, display_order
) VALUES (
  'cyclone-gabrielle-2023', 'Gabrielle', 'Cyclone Gabrielle',
  2023, '2023 Pacific', 'SP',
  3, 'Cyclone',
  NULL, NULL,
  '2023-06-01',
  NULL, NULL,
  ARRAY[]::TEXT[],
  'Cyclone Gabrielle was a cyclone during the 2023 Pacific season.',
  '## Overview

Cyclone Gabrielle was a cyclone during the 2023 Pacific season.

## Key Facts

See structured data above.

## Sources

- [Wikipedia](https://en.wikipedia.org/wiki/Cyclone_Gabrielle_(2023))
- [NOAA NHC](https://www.nhc.noaa.gov/)
',
  ARRAY[]::TEXT[],
  '[{"title":"Wikipedia — Cyclone Gabrielle","url":"https://en.wikipedia.org/wiki/Cyclone_Gabrielle_(2023)","type":"wiki"},{"title":"NOAA National Hurricane Center","url":"https://www.nhc.noaa.gov/","type":"official"}]'::JSONB,
  NULL,
  FALSE,
  NULL
) ON CONFLICT (slug) DO NOTHING;